# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 837c4fa37eddde551b3a4fe3b74d2f1fb10c8698b088bc430745fd7b6268ddb910bf9a2dda06e393c6014a8086195be357935729694d2cc14fe1e64261a74bdb

test:
  secret_key_base: 2cbaffe2a9b455f5fb2716c70d2f77b8afb36e6e9a1285d3dbec12f6400245b776ac67027ddc3186d2a2a659220f686f6aa66a3e29a909cafd53bbdec5ccbd1f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
